### ISSUE TITLE
[DUP] sub-0041_ses-03_task-social_acq-mb8_run-02

### ISSUE THREAD

**Issue by jungheejung** [spatialtopology/spacetop-prep#58]
### TODO

- [x] Need to remove the dups and the bold data altogether
- [x] remove bold data from fmriprep, too
- [x] confirm that the behavioral data doesn't exist for this run

### scannotes
- Medoc went over the allowed temp and errored out and we didn't catch it. So we repeated the second run. It failed again with error saying the tsa2 did not reach the the temperature in the required time. Then the pre-test failed. Debugging now

**Comment by jungheejung** [comment]
- [x] Need to remove the dups and the bold data altogether
- [x] confirm that the behavioral data doesn't exist for this run

**Comment by jungheejung** [comment]
- [ ] remove bold data from fmriprep
