### ISSUE TITLE
[MISSING DATALAD] sub-0103_ses-02 missing

### ISSUE THREAD

**Issue by jungheejung** [spatialtopology/spacetop-prep#68]
### TODO

- [ ] need to search for missing session

### scannotes
All scans were completed
Faces: froze. hard reboot.

**Comment by jungheejung** [comment]
Yarik suggestions
1. check `.heudiconv/spacetop_subject_id.csv`
2.

**Comment by yarikoptic** [comment]
there might be more either missing or just mislabeled somehow:

```shell
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ awk -F, '/^sub-/{print $1"/"$5;}' < .heudiconv/spacetop_subject_id.csv | while read f; do [ -e "$f" ] || echo $f is missing; done | nl
     1  sub-0007/ses-04 is missing
     2  sub-0023/ses-03 is missing
     3  sub-0041/ses-02 is missing
     4  sub-0039/ses-03 is missing
     5  sub-0046/ses-01 is missing
     6  sub-0041/ses-04 is missing
     7  sub-0064/ses-02 is missing
     8  sub-0064/ses-03 is missing
     9  sub-0075/ses-04 is missing
    10  sub-0094/ses-02 is missing
    11  sub-0105/ses-01 is missing
    12  sub-0103/ses-02 is missing
    13  sub-0123/ses-03 is missing
    14  sub-0128/ses-04 is missing
    15  sub-0126/ses-04 is missing
```

and we have 412 converted and 430 entries:

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep '^sub-' .heudiconv/spacetop_subject_id.csv | nl | tail -n 2
   429  sub-0132,SID001282,A004935,07/08/2022,ses-04,
   430  sub-0133,SID002297,A004936,07/08/2022,ses-04,
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ /bin/ls -d sub-0*/ses-* | nl | tail -n 2
   411  sub-0133/ses-03
   412  sub-0133/ses-04
```

so something is still odd... 

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ awk -F, '/^sub-/{print $1"/"$5;}' < .heudiconv/spacetop_subject_id.csv | sort | uniq -c | sort -n  | grep '^ *2'
      2 sub-0025/ses-02
      2 sub-0052/ses-03
      2 sub-0057/ses-01
      2 sub-0126/ses-02
```

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep sub-0025.*ses-02 .heudiconv/spacetop_subject_id.csv
sub-0025,SID001878,A003631,05/17/2021,ses-02,REMOVED - missing head coil
sub-0025,SID001878,A004803,05/18/2022,ses-02,use - rescanned for missing headcoil
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep sub-0052.*ses-03 .heudiconv/spacetop_subject_id.csv
sub-0052,SID001957,A003923,08/16/2021,ses-03,
sub-0052,SID001957,A003955,08/26/2021,ses-03,Collecting missing ses-03 data. Should be merged in BIDS with DICOM/2021/08/16/A003923.
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep sub-0057.*ses-01 .heudiconv/spacetop_subject_id.csv
sub-0057,SID001971,A003935,08/19/2021,ses-01,
sub-0057,SID001971,A003960,08/26/2021,ses-01,Collecting missing ses-01 data. Should be merged in BIDS with DICOM/2021/08/19/A003935.
```

the only unclear one:

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep sub-0126.*ses-02 .heudiconv/spacetop_subject_id.csv
sub-0126,SID002215,A004802,05/18/2022,ses-02,
sub-0126,SID002215,A004835,05/26/2022,ses-02,
```

so there two scanning sessions and no comment... apparently first one was a canceled on

```
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ ls /inbox/DICOM/2022/05/18/A004802/
001-anat-scout_ses-02          003-anat-scout_ses-02_MPR_cor  005-anat-scout_ses-02          007-anat-scout_ses-02_MPR_cor
002-anat-scout_ses-02_MPR_sag  004-anat-scout_ses-02_MPR_tra  006-anat-scout_ses-02_MPR_sag  008-anat-scout_ses-02_MPR_tra

bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ ls /inbox/DICOM/2022/05/26/A004835
001-anat-scout_ses-02                             018-func_run-02_task-faces_acq-ap-mb8
002-anat-scout_ses-02_MPR_sag                     019-func_run-03_task-faces_acq-ap-mb8_SBRef
003-anat-scout_ses-02_MPR_cor                     020-func_run-03_task-faces_acq-ap-mb8
004-anat-scout_ses-02_MPR_tra                     021-anat-scout_ses-02
005-fmap-epi_dir-ap_acq-mb8_run-01                022-anat-scout_ses-02_MPR_sag
006-fmap-epi_dir-pa_acq-mb8_run-01                023-anat-scout_ses-02_MPR_cor
007-func_run-01_task-narratives_acq-ap-mb8_SBRef  024-anat-scout_ses-02_MPR_tra
008-func_run-01_task-narratives_acq-ap-mb8        025-fmap-epi_dir-ap_acq-mb8_run-02
009-func_run-02_task-narratives_acq-ap-mb8_SBRef  026-fmap-epi_dir-pa_acq-mb8_run-02
010-func_run-02_task-narratives_acq-ap-mb8        027-func_run-01_task-alignvideo_acq-ap-mb8_SBRef
011-func_run-03_task-narratives_acq-ap-mb8_SBRef  028-func_run-01_task-alignvideo_acq-ap-mb8
012-func_run-03_task-narratives_acq-ap-mb8        029-func_run-02_task-alignvideo_acq-ap-mb8_SBRef
013-func_run-04_task-narratives_acq-ap-mb8_SBRef  030-func_run-02_task-alignvideo_acq-ap-mb8
014-func_run-04_task-narratives_acq-ap-mb8        031-func_run-03_task-alignvideo_acq-ap-mb8_SBRef
015-func_run-01_task-faces_acq-ap-mb8_SBRef       032-func_run-03_task-alignvideo_acq-ap-mb8
016-func_run-01_task-faces_acq-ap-mb8             033-func_run-04_task-alignvideo_acq-ap-mb8_SBRef
017-func_run-02_task-faces_acq-ap-mb8_SBRef       034-func_run-04_task-alignvideo_acq-ap-mb8
```

I added a note

**Comment by yarikoptic** [comment]
got the algebra of "off 1" : we are missing an entry in csv for one converted subject session present in the dataset
```shell
bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ for f in sub-0*/ses-*; do sub=${f%/*}; ses=${f#*/}; grep -q "^$sub,.*,$ses," .heudiconv/spacetop_subject_id.csv || echo $f is missing; done
sub-0090/ses-01 is missing

bids@rolando:/inbox/BIDS/Wager/Wager/1076_spacetop$ grep sub-0090 .heudiconv/spacetop_subject_id.csv
sub-0090,SID002048,A004235,11/07/2021,ses-02,
sub-0090,SID002048,A004255,11/11/2021,ses-03,
sub-0090,SID002048,A004325,01/13/2022,ses-04,
```

**Comment by bogpetre** [comment]
Any updates on these missing scans? I see sub-0075 ses-04 has been added to the BIDS directory (/dartfs-hpc/rc/lab/C/CANlab/labdata/data/spacetop/dartmouth/) but other subjects like sub-0007 ses-04 are still not there. I believe heejung took a closer look at 0075 for me last week, but I don't know the full story and whether or not she only looked for this participant or if there was a more systematic effort to dig all of these guys up.

**Comment by jungheejung** [comment]
- [x] sub-0007/ses-04 is missing
- [missing for a reason] sub-0023/ses-03 is missing (spacetop_subject_id.csv: REMOVED - missing head coil)
- [x] sub-0041/ses-02 is missing
- [missing for a reason]  sub-0039/ses-03 is missing (spacetop_subject_id.csv: REMOVED - missing head coil)
- [x] sub-0046/ses-01 is missing
- [x] sub-0041/ses-04 is missing
- [x] sub-0064/ses-02 is missing
- [x]  sub-0064/ses-03 is missing
- [x]  sub-0075/ses-04 is missing
- [x]  sub-0094/ses-02 is missing
- [x] sub-0105/ses-01 is missing
- [x] sub-0103/ses-02 is missing
- [missing for a reason]  sub-0123/ses-03 is missing (SKIP - subject withdrew)
- [x] sub-0128/ses-04 is missing
- [x] sub-0126/ses-04 is missing
