### ISSUE TITLE
[ERR] BIDS validator issue 01: odd duplicate names

### ISSUE THREAD

**Issue by jungheejung** [spatialtopology/spacetop-prep#86]
### TODO

- [x] Need to manually resolve or feed it through Heudiconv

### fmriprep output
```
	[31m1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)[39m
		./sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-ap_run+-PVC-run-04_epi.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0016_ses-01_acq-mb8_dir-ap_run+-PVC-run-04_epi.json
		./sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-ap_run+-PVC-run-04_epi.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0016_ses-01_acq-mb8_dir-ap_run+-PVC-run-04_epi.nii.gz
		./sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-pa_run=-PVS-run-04_epi.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0016_ses-01_acq-mb8_dir-pa_run=-PVS-run-04_epi.json
		./sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-pa_run=-PVS-run-04_epi.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0016_ses-01_acq-mb8_dir-pa_run=-PVS-run-04_epi.nii.gz
		./sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-ap_alignvideos_run-02_epi.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0017_ses-01_acq-mb8_dir-ap_alignvideos_run-02_epi.json
		./sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-ap_alignvideos_run-02_epi.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0017_ses-01_acq-mb8_dir-ap_alignvideos_run-02_epi.nii.gz
		./sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-pa_alignvideos_run-02_epi.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0017_ses-01_acq-mb8_dir-pa_alignvideos_run-02_epi.json
		./sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-pa_alignvideos_run-02_epi.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0017_ses-01_acq-mb8_dir-pa_alignvideos_run-02_epi.nii.gz
		./sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8_51_run-03_bold.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0025_ses-03_task-social_acq-mb8_51_run-03_bold.json
		./sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8_51_run-03_bold.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0025_ses-03_task-social_acq-mb8_51_run-03_bold.nii.gz
		./sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8_51_run-03_sbref.json
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0025_ses-03_task-social_acq-mb8_51_run-03_sbref.json
		./sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8_51_run-03_sbref.nii.gz
			Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
			Evidence: sub-0025_ses-03_task-social_acq-mb8_51_run-03_sbref.nii.gz
```

### scannotes
(Insert scannotes from ST_participants)

**Comment by jungheejung** [comment]
More:

```
./sub-0050/ses-02/fmap/sub-0050_ses-02_acq-mb8_dir-pa_run-51_epi.nii.gz
./sub-0050/ses-02/fmap/sub-0050_ses-02_acq-mb8_dir-ap_run-51_epi.nii.gz
./sub-0023/ses-01/fmap/sub-0023_ses-01_acq-mb8_dir-pa_run-51_epi.nii.gz
./sub-0023/ses-01/fmap/sub-0023_ses-01_acq-mb8_dir-ap_run-51_epi.nii.gz
./sub-0023/ses-02/fmap/sub-0023_ses-02_acq-mb8_dir-pa_run-51_epi.nii.gz
./sub-0023/ses-02/fmap/sub-0023_ses-02_acq-mb8_dir-ap_run-51_epi.nii.gz
./sub-0069/ses-01/fmap/sub-0069_ses-01_acq-mb8_dir-pa_run-51_epi.nii.gz
./sub-0069/ses-01/fmap/sub-0069_ses-01_acq-mb8_dir-ap_run-51_epi.nii.gz
```

**Comment by jungheejung** [comment]
```
(base) [f0042x1@discovery-01 fmap]$ grep '"AcquisitionTime": "' sub-0050_ses-02_acq-mb8_dir-pa*epi.json
sub-0050_ses-02_acq-mb8_dir-pa_run-01_epi.json:  "AcquisitionTime": "16:21:20.342500",
sub-0050_ses-02_acq-mb8_dir-pa_run-02_epi.json:  "AcquisitionTime": "17:35:45.365000",
sub-0050_ses-02_acq-mb8_dir-pa_run-51_epi.json:  "AcquisitionTime": "17:17:34.347500",
```

- [ ] rename run-02 to run-03
- [ ] ```code/rename_file --swap --all-extensions sub-0050/ses-02/fmap/sub-0050_ses-02_acq-mb8_dir-pa_run-{02,03}_epi.json```
- [ ] ```code/rename_file --swap --all-extensions sub-0050/ses-02/fmap/sub-0050_ses-02_acq-mb8_dir-ap_run-{02,03}_epi.json```
- [x] rename run-51 to run-02
- [x] ```code/rename_file --swap --all-extensions sub-0050/ses-02/fmap/sub-0050_ses-02_acq-mb8_dir-ap_run-{51,02}_epi.json```
\\
