### ISSUE TITLE
[DEP] BOLD file to delete

### ISSUE THREAD

**Issue by jungheejung** [spatialtopology/spacetop-prep#96]
### TODO

- [x] Delete fMRI files after cross comparing scannotes
- [x] Scannotes appended to problematic scans
- [x] Check `spacetop-prep/spacetop_prep/datalad/delete_bold.tsv` https://github.com/spatialtopology/spacetop-prep/blob/dcfb22ee1e33bd4b325e802655b6f7b5a083953b/spacetop_prep/datalad/delete_bold.tsv
- [x] derived through: https://github.com/spatialtopology/spacetop-prep/blob/master/spacetop_prep/datalad/remove_scannotes_nodata.py

### fmriprep output
```
NO BOLD - SCANNOTES DELETE
BOLD EXISTS
Acquisition time 102 is less than 872. 
Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0007/ses-03/func/sub-0007_ses-03_task-social_acq-mb8_run-06_bold.nii.gz
DELETE: sub-0007_ses-03_task-social_acq-mb8_run-06*
 
BOLD EXISTS
Acquisition time 429 is less than 872. 
Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0026/ses-01/func/sub-0026_ses-01_task-social_acq-mb8_run-02_bold.nii.gz
DELETE: sub-0026_ses-01_task-social_acq-mb8_run-02*
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-alignvideo_acq-mb8_run-01_bold.nii.gz
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-alignvideo_acq-mb8_run-02_bold.nii.gz

Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-alignvideo_acq-mb8_run-03_bold.nii.gz
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-01_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-02_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-03_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-04_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-05_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0052/ses-03/func/sub-0052_ses-03_task-social_acq-mb8_run-06_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-alignvideo_acq-mb8_run-04_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
NO BOLD - SCANNOTES DELETE
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-01_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-02_bold.nii.gz
NO BOLD - SCANNOTES DELETE
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-03_bold.nii.gz
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-04_bold.nii.gz
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-05_bold.nii.gz

BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-social_acq-mb8_run-06_bold.nii.gz

BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-alignvideo_acq-mb8_run-01_bold.nii.gz

BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-alignvideo_acq-mb8_run-02_bold.nii.gz

BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0057/ses-01/func/sub-0057_ses-01_task-alignvideo_acq-mb8_run-03_bold.nii.gz

BOLD EXISTS
Acquisition time 240 is less than 872. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0064/ses-04/func/sub-0064_ses-04_task-social_acq-mb8_run-01_bold.nii.gz
DELETE: sub-0064_ses-04_task-social_acq-mb8_run-01*
 
BOLD EXISTS
Acquisition time 35 is less than 1209. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0068/ses-01/func/sub-0068_ses-01_task-alignvideo_acq-mb8_run-04_bold.nii.gz
DELETE: sub-0068_ses-01_task-alignvideo_acq-mb8_run-04*
 
BOLD EXISTS
Acquisition time is acceptable for file: /Users/h/Documents/projects_local/1076_spacetop/sub-0075/ses-01/func/sub-0075_ses-01_task-social_acq-mb8_run-01_bold.nii.gz

BOLD EXISTS
Acquisition time 170 is less than 872. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0084/ses-03/func/sub-0084_ses-03_task-social_acq-mb8_run-03_bold.nii.gz
DELETE: sub-0084_ses-03_task-social_acq-mb8_run-03*
 
 
BOLD EXISTS
Acquisition time 862 is less than 1268. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0094/ses-04/func/sub-0094_ses-04_task-alignvideo_acq-mb8_run-01_bold.nii.gz
DELETE: sub-0094_ses-04_task-alignvideo_acq-mb8_run-01*
 
BOLD EXISTS
Acquisition time 831 is less than 1158. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0118/ses-02/func/sub-0118_ses-02_task-alignvideo_acq-mb8_run-03_bold.nii.gz
DELETE: sub-0118_ses-02_task-alignvideo_acq-mb8_run-03*
 
BOLD EXISTS
Acquisition time 257 is less than 872. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0131/ses-01/func/sub-0131_ses-01_task-social_acq-mb8_run-05_bold.nii.gz
DELETE: sub-0131_ses-01_task-social_acq-mb8_run-05*
 
BOLD EXISTS
Acquisition time 605 is less than 872. Ready to delete: /Users/h/Documents/projects_local/1076_spacetop/sub-0131/ses-04/func/sub-0131_ses-04_task-social_acq-mb8_run-01_bold.nii.gz
DELETE: sub-0131_ses-04_task-social_acq-mb8_run-01*

```

### scannotes
(Insert scannotes from ST_participants)

**Comment by jungheejung** [comment]
DELETE
```
sub-0001_ses-01_task-social_acq-mb8_run-01*
sub-0001_ses-01_task-social_acq-mb8_run-02*
sub-0001_ses-01_task-social_acq-mb8_run-03*
sub-0001_ses-01_task-social_acq-mb8_run-04*
sub-0001_ses-01_task-social_acq-mb8_run-05*
sub-0001_ses-01_task-social_acq-mb8_run-06*
sub-0002_ses-03_task-social_acq-mb8_run-04*
sub-0002_ses-03_task-social_acq-mb8_run-04*
sub-0002_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0003_ses-03_task-social_acq-mb8_run-01*
sub-0003_ses-03_task-social_acq-mb8_run-02*
sub-0003_ses-03_task-social_acq-mb8_run-03*
sub-0003_ses-03_task-social_acq-mb8_run-04*
sub-0003_ses-03_task-social_acq-mb8_run-05*
sub-0003_ses-03_task-social_acq-mb8_run-06*
sub-0003_ses-04_task-social_acq-mb8_run-01*
sub-0003_ses-04_task-social_acq-mb8_run-02*
sub-0003_ses-04_task-social_acq-mb8_run-03*
sub-0003_ses-04_task-social_acq-mb8_run-04*
sub-0003_ses-04_task-social_acq-mb8_run-05*
sub-0003_ses-04_task-social_acq-mb8_run-06*
sub-0004_ses-03_task-social_acq-mb8_run-01*
sub-0004_ses-03_task-social_acq-mb8_run-02*
sub-0004_ses-03_task-social_acq-mb8_run-03*
sub-0004_ses-03_task-social_acq-mb8_run-04*
sub-0004_ses-03_task-social_acq-mb8_run-05*
sub-0004_ses-03_task-social_acq-mb8_run-06*
sub-0004_ses-04_task-social_acq-mb8_run-01*
sub-0004_ses-04_task-social_acq-mb8_run-02*
sub-0004_ses-04_task-social_acq-mb8_run-03*
sub-0004_ses-04_task-social_acq-mb8_run-04*
sub-0004_ses-04_task-social_acq-mb8_run-05*
sub-0004_ses-04_task-social_acq-mb8_run-06*
sub-0006_ses-04_task-fractional_acq-mb8_run-01*
sub-0006_ses-04_task-fractional_acq-mb8_run-02*
sub-0007_ses-03_task-social_acq-mb8_run-06*
sub-0007_ses-03_task-social_acq-mb8_run-06*
sub-0009_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0009_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0011_ses-03_task-social_acq-mb8_run-02*
sub-0011_ses-03_task-alignvideo_acq-mb8_run-01*
sub-0019_ses-03_task-social_acq-mb8_run-02*
sub-0020_ses-01_task-social_acq-mb8_run-01*
sub-0020_ses-04_task-social_acq-mb8_run-06*
sub-0021_ses-01_task-social_acq-mb8_run-06*
sub-0021_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0021_ses-03_task-social_acq-mb8_run-04*
sub-0021_ses-03_task-social_acq-mb8_run-05*
sub-0021_ses-04_task-social_acq-mb8_run-03*
sub-0021_ses-04_task-social_acq-mb8_run-06*
sub-0024_ses-01_task-social_acq-mb8_run-04*
sub-0024_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0024_ses-03_task-social_acq-mb8_run-03*
sub-0024_ses-03_task-social_acq-mb8_run-06*
sub-0024_ses-04_task-social_acq-mb8_run-01*
sub-0024_ses-04_task-social_acq-mb8_run-05*
sub-0025_ses-01_task-social_acq-mb8_run-04*
sub-0025_ses-01_task-social_acq-mb8_run-05*
sub-0026_ses-01_task-social_acq-mb8_run-02*
sub-0026_ses-01_task-social_acq-mb8_run-02*
sub-0026_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0028_ses-01_task-alignvideo_acq-mb8_run-02*
sub-0028_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0028_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0029_ses-02_task-faces_acq-mb8_run-03*
sub-0035_ses-03_task-social_acq-mb8_run-02*
sub-0035_ses-03_task-social_acq-mb8_run-05*
sub-0039_ses-01_task-social_acq-mb8_run-02*
sub-0039_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0039_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0040_ses-03_task-social_acq-mb8_run-02*
sub-0040_ses-03_task-social_acq-mb8_run-04*
sub-0041_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0041_ses-03_task-social_acq-mb8_run-02*
sub-0041_ses-03_task-social_acq-mb8_run-05*
sub-0046_ses-02_task-faces_acq-mb8_run-03*
sub-0052_ses-01_task-social_acq-mb8_run-01*
sub-0052_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-01*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-02*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-03*
sub-0052_ses-03_task-social_acq-mb8_run-01*
sub-0052_ses-03_task-social_acq-mb8_run-02*
sub-0052_ses-03_task-social_acq-mb8_run-03*
sub-0052_ses-03_task-social_acq-mb8_run-04*
sub-0052_ses-03_task-social_acq-mb8_run-05*
sub-0052_ses-03_task-social_acq-mb8_run-06*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-01*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-02*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-03*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-04*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0057_ses-01_unknown-task_acq-mb8_unknown-run*
sub-0057_ses-01_task-social_acq-mb8_run-01*
sub-0057_ses-01_task-social_acq-mb8_run-02*
sub-0057_ses-01_task-social_acq-mb8_run-03*
sub-0057_ses-01_task-social_acq-mb8_run-04*
sub-0057_ses-01_task-social_acq-mb8_run-05*
sub-0057_ses-01_task-social_acq-mb8_run-06*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-01*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-02*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0057_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0057_ses-04_task-alignvideo_acq-mb8_run-02*
sub-0058_ses-01_task-social_acq-mb8_run-01*
sub-0059_ses-04_task-social_acq-mb8_run-02*
sub-0059_ses-04_task-social_acq-mb8_run-05*
sub-0063_ses-01_task-social_acq-mb8_run-02*
sub-0063_ses-01_task-social_acq-mb8_run-03*
sub-0063_ses-01_task-social_acq-mb8_run-04*
sub-0063_ses-01_task-social_acq-mb8_run-05*
sub-0063_ses-01_task-social_acq-mb8_run-06*
sub-0063_ses-01_task-alignvideo_acq-mb8_run-01*
sub-0063_ses-01_task-alignvideo_acq-mb8_run-02*
sub-0063_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0063_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0064_ses-03_task-social_acq-mb8_run-03*
sub-0064_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0064_ses-04_task-social_acq-mb8_run-01*
sub-0064_ses-04_task-social_acq-mb8_run-01*
sub-0064_ses-04_task-social_acq-mb8_run-05*
sub-0066_ses-01_task-social_acq-mb8_run-02*
sub-0066_ses-01_task-social_acq-mb8_run-04*
sub-0066_ses-03_task-social_acq-mb8_run-02*
sub-0066_ses-03_task-social_acq-mb8_run-05*
sub-0068_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0068_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0069_ses-03_task-social_acq-mb8_run-01*
sub-0069_ses-03_task-social_acq-mb8_run-06*
sub-0069_ses-01_task-social_acq-mb8_run-03*
sub-0069_ses-04_task-social_acq-mb8_run-01*
sub-0069_ses-04_task-social_acq-mb8_run-05*
sub-0070_ses-01_task-social_acq-mb8_run-03*
sub-0070_ses-01_task-social_acq-mb8_run-06*
sub-0070_ses-03_task-social_acq-mb8_run-03*
sub-0070_ses-03_task-social_acq-mb8_run-04*
sub-0071_ses-01_task-social_acq-mb8_run-02*
sub-0071_ses-01_task-social_acq-mb8_run-02*
sub-0071_ses-01_task-social_acq-mb8_run-05*
sub-0074_ses-04_task-social_acq-mb8_run-05*
sub-0074_ses-04_task-social_acq-mb8_run-06*
sub-0074_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0074_ses-04_task-alignvideo_acq-mb8_run-02*
sub-0075_ses-01_task-social_acq-mb8_run-01*
sub-0075_ses-01_task-social_acq-mb8_run-05*
sub-0075_ses-03_task-social_acq-mb8_run-02*
sub-0075_ses-03_task-social_acq-mb8_run-05*
sub-0076_ses-01_task-social_acq-mb8_run-02*
sub-0076_ses-01_task-social_acq-mb8_run-04*
sub-0076_ses-03_task-social_acq-mb8_run-03*
sub-0076_ses-03_task-social_acq-mb8_run-06*
sub-0077_ses-01_task-social_acq-mb8_run-03*
sub-0077_ses-01_task-social_acq-mb8_run-04*
sub-0079_ses-01_task-social_acq-mb8_run-03*
sub-0079_ses-01_task-social_acq-mb8_run-04*
sub-0079_ses-03_task-social_acq-mb8_run-02*
sub-0081_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0082_ses-01_task-social_acq-mb8_run-01*
sub-0082_ses-01_task-social_acq-mb8_run-02*
sub-0082_ses-01_task-social_acq-mb8_run-03*
sub-0082_ses-01_task-social_acq-mb8_run-04*
sub-0082_ses-01_task-social_acq-mb8_run-05*
sub-0082_ses-01_task-social_acq-mb8_run-06*
sub-0084_ses-03_task-social_acq-mb8_run-03*
sub-0084_ses-03_task-social_acq-mb8_run-03*
sub-0084_ses-03_task-social_acq-mb8_run-06*
sub-0085_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0091_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0091_ses-04_task-alignvideo_acq-mb8_run-02*
sub-0094_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0094_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0103_ses-01_task-social_acq-mb8_run-04*
sub-0103_ses-01_task-social_acq-mb8_run-05*
sub-0103_ses-01_task-social_acq-mb8_run-06*
sub-0103_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0111_ses-04_task-social_acq-mb8_run-05*
sub-0111_ses-04_task-social_acq-mb8_run-05*
sub-0112_ses-01_task-social_acq-mb8_run-01*
sub-0112_ses-01_task-social_acq-mb8_run-06*
sub-0112_ses-04_task-social_acq-mb8_run-03*
sub-0112_ses-04_task-social_acq-mb8_run-04*
sub-0112_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0112_ses-04_task-alignvideo_acq-mb8_run-02*
sub-0116_ses-02_task-faces_acq-mb8_run-03*
sub-0116_ses-02_task-faces_acq-mb8_run-03*
sub-0118_ses-02_task-alignvideo_acq-mb8_run-03*
sub-0118_ses-02_task-alignvideo_acq-mb8_run-03*
sub-0118_ses-02_task-alignvideo_acq-mb8_run-04*
sub-0123_ses-03_task-social_acq-mb8_run-04*
sub-0123_ses-03_task-social_acq-mb8_run-05*
sub-0123_ses-03_task-social_acq-mb8_run-06*
sub-0123_ses-03_unknown-task_acq-mb8_unknown-run*
sub-0123_ses-03_task-alignvideo_acq-mb8_run-01*
sub-0123_ses-03_task-alignvideo_acq-mb8_run-02*
sub-0123_ses-03_task-alignvideo_acq-mb8_run-03*
sub-0124_ses-01_task-social_acq-mb8_run-03*
sub-0128_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0128_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0128_ses-04_task-social_acq-mb8_run-05*
sub-0131_ses-01_task-t1_acq-mb8_(structural)*
sub-0131_ses-01_task-social_acq-mb8_run-05*
sub-0131_ses-01_task-social_acq-mb8_run-05*
sub-0131_ses-04_task-social_acq-mb8_run-01*
sub-0131_ses-04_task-social_acq-mb8_run-01*
```

**Comment by jungheejung** [comment]
INVESTIGATE
```
sub-0001_ses-01_task-social_acq-mb8_run-01*
sub-0001_ses-01_task-social_acq-mb8_run-02*
sub-0001_ses-01_task-social_acq-mb8_run-03*
sub-0003_ses-03_task-social_acq-mb8_run-01*
sub-0003_ses-03_task-social_acq-mb8_run-02*
sub-0003_ses-03_task-social_acq-mb8_run-03*
sub-0003_ses-03_task-social_acq-mb8_run-04*
sub-0003_ses-03_task-social_acq-mb8_run-05*
sub-0003_ses-03_task-social_acq-mb8_run-06*
sub-0003_ses-04_task-social_acq-mb8_run-01*
sub-0003_ses-04_task-social_acq-mb8_run-02*
sub-0003_ses-04_task-social_acq-mb8_run-03*
sub-0003_ses-04_task-social_acq-mb8_run-04*
sub-0003_ses-04_task-social_acq-mb8_run-05*
sub-0003_ses-04_task-social_acq-mb8_run-06*
sub-0004_ses-03_task-social_acq-mb8_run-01*
sub-0004_ses-03_task-social_acq-mb8_run-02*
sub-0004_ses-03_task-social_acq-mb8_run-03*
sub-0004_ses-03_task-social_acq-mb8_run-04*
sub-0004_ses-03_task-social_acq-mb8_run-05*
sub-0004_ses-03_task-social_acq-mb8_run-06*
sub-0004_ses-04_task-social_acq-mb8_run-01*
sub-0004_ses-04_task-social_acq-mb8_run-02*
sub-0004_ses-04_task-social_acq-mb8_run-03*
sub-0004_ses-04_task-social_acq-mb8_run-04*
sub-0004_ses-04_task-social_acq-mb8_run-05*
sub-0004_ses-04_task-social_acq-mb8_run-06*
sub-0011_ses-03_task-social_acq-mb8_run-02*
sub-0011_ses-03_task-alignvideo_acq-mb8_run-01*
sub-0019_ses-03_task-social_acq-mb8_run-02*
sub-0020_ses-01_task-social_acq-mb8_run-01*
sub-0020_ses-04_task-social_acq-mb8_run-06*
sub-0021_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0021_ses-03_task-social_acq-mb8_run-04*
sub-0021_ses-03_task-social_acq-mb8_run-05*
sub-0021_ses-04_task-social_acq-mb8_run-03*
sub-0021_ses-04_task-social_acq-mb8_run-06*
sub-0024_ses-03_task-social_acq-mb8_run-03*
sub-0025_ses-01_task-social_acq-mb8_run-04*
sub-0025_ses-01_task-social_acq-mb8_run-05*
sub-0039_ses-01_task-social_acq-mb8_run-02*
sub-0046_ses-02_task-faces_acq-mb8_run-03*
sub-0052_ses-01_task-social_acq-mb8_run-01*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-01*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-02*
sub-0052_ses-03_task-alignvideo_acq-mb8_run-03*
sub-0052_ses-03_task-social_acq-mb8_run-01*
sub-0052_ses-03_task-social_acq-mb8_run-02*
sub-0052_ses-03_task-social_acq-mb8_run-03*
sub-0052_ses-03_task-social_acq-mb8_run-04*
sub-0052_ses-03_task-social_acq-mb8_run-05*
sub-0052_ses-03_task-social_acq-mb8_run-06*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-01*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-02*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-03*
sub-0056_ses-02_task-alignvideo_acq-mb8_run-04*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-04*
sub-0057_ses-01_task-social_acq-mb8_run-01*
sub-0057_ses-01_task-social_acq-mb8_run-02*
sub-0057_ses-01_task-social_acq-mb8_run-03*
sub-0057_ses-01_task-social_acq-mb8_run-04*
sub-0057_ses-01_task-social_acq-mb8_run-05*
sub-0057_ses-01_task-social_acq-mb8_run-06*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-01*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-02*
sub-0057_ses-01_task-alignvideo_acq-mb8_run-03*
sub-0058_ses-01_task-social_acq-mb8_run-01*
sub-0069_ses-01_task-social_acq-mb8_run-03*
sub-0075_ses-01_task-social_acq-mb8_run-01*
sub-0079_ses-03_task-social_acq-mb8_run-02*
sub-0112_ses-01_task-social_acq-mb8_run-01*
sub-0112_ses-01_task-social_acq-mb8_run-06*
sub-0112_ses-04_task-social_acq-mb8_run-03*
sub-0112_ses-04_task-social_acq-mb8_run-04*
sub-0112_ses-04_task-alignvideo_acq-mb8_run-01*
sub-0112_ses-04_task-alignvideo_acq-mb8_run-02*
sub-0124_ses-01_task-social_acq-mb8_run-03*
sub-0128_ses-04_task-social_acq-mb8_run-05*


```
