### ISSUE TITLE
[BUG] TODO in events files

### ISSUE THREAD

**Issue by jungheejung** [spatialtopology/spacetop-prep#99]
### Which module is this from?

beh

### What is the issue?

Empty `events.tsv` files

### What was your expected behavior?

To have it populated based on `d_beh` git repo

### How can we reproduce this?

git grep TODO on datalad dataset

### Any additional context?

Need to resolve these TODOs manually
* Either the temporary behavioral files exist and needs to be converted to BIDS
* or the brain data does not exist and needs to be removed altogether
* Need to cross-check scannotes and determine whether to keep or delete

* #C2: Full data exists. not sure why it wasn't converted. Solution: convert these specific Participants
* #C1. TEMP_beh exists.  → copy over temp data to d_beh. push to github.
* #C3. typo
* #C4. No temp file

- [x] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-01_events.tsv → add onset times manually `DONE` via matlab code [alignvideo python script](https://github.com/spatialtopology/spacetop-prep/blob/b09cfb932c5bffd62c25239a7b788baeae89eb20/spacetop_prep/events/bidsify_alignvideos_ENH.py ) in #101 
- [x] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-02_events.tsv → add onset times manually `DONE` via matlab code [alignvideo python script](https://github.com/spatialtopology/spacetop-prep/blob/b09cfb932c5bffd62c25239a7b788baeae89eb20/spacetop_prep/events/bidsify_alignvideos_ENH.py ) in #101 
- [x] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-03_events.tsv → add onset times manually `DONE` via matlab code [alignvideo python script](https://github.com/spatialtopology/spacetop-prep/blob/b09cfb932c5bffd62c25239a7b788baeae89eb20/spacetop_prep/events/bidsify_alignvideos_ENH.py ) in #101 
- [x] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-04_events.tsv → add onset times manually `DONE` via matlab code [alignvideo python script](https://github.com/spatialtopology/spacetop-prep/blob/b09cfb932c5bffd62c25239a7b788baeae89eb20/spacetop_prep/events/bidsify_alignvideos_ENH.py ) in #101 
- [x] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [x] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [x] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [x] sub-0001/ses-04/func/sub-0001_ses-04_task-fractional_acq-mb8_run-01_events.tsv DONE: resolved via: https://github.com/spatialtopology/spacetop-prep/blob/master/spacetop_prep/datalad/resolve_missingevents/s04_sub_0001_task_tomsaxe.m

- [x] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-01_events.tsv → exclude
- [x] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-02_events.tsv → exclude
- [x] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-03_events.tsv → exclude
- [x] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-01_events.tsv → #C2. check column?
- [x] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-02_events.tsv → #C2. check column?
- [x] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-03_events.tsv → #C2. check column?
- [x] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-01_events.tsv → #C2. check column?
- [x] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-02_events.tsv → #C2. check column?
- [x] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-03_events.tsv → #C2. check column?
- [x] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-01_events.tsv → #C3. file exists under sub-005
- [x] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-02_events.tsv → #C3. file exists under sub-005
- [x] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-03_events.tsv → #C3. file exists under sub-005 WHY NOT? Typo in filename DONE. filename harmonized and rerun datalad
- [ ] sub-0006/ses-04/func/sub-0006_ses-04_task-fractional_acq-mb8_run-01_events.tsv → func exists in Rolando, but not in datalad
- [ ] sub-0006/ses-04/func/sub-0006_ses-04_task-fractional_acq-mb8_run-02_events.tsv  → func exists in Rolando, but not in datalad
- [x] sub-0007/ses-03/func/sub-0007_ses-03_task-social_acq-mb8_run-06_events.tsv → #C4. No TEMP data
- [x] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-01_events.tsv → #C1 TEMP_beh exists. FLAG no response
- [x] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-02_events.tsv → #C1 TEMP_beh exists. FLAG no response
- [x] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-03_events.tsv → #C1 TEMP_beh exists. FLAG no response
- [x] sub-0008/ses-04/func/sub-0008_ses-04_task-social_acq-mb8_run-05_events.tsv → # NEED TO RE RUN. SOME ONSETS ARE NEGATIVE, because trials were invalid C1 TEMP_beh exists
- [x] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-01_events.tsv → #C4NEED MANUAL INSERT deleted with #102
- [x] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-02_events.tsv → #C4NEED MANUAL INSERT deleted with #102
- [x] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-03_events.tsv → #C4 NEED MANUAL INSERT deleted with #102
- [x] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-04_events.tsv → #C4 NEED MANUAL INSERT deleted with #102
- [x] sub-0011/ses-02/func/sub-0011_ses-02_task-narratives_acq-mb8_run-02_events.tsv → #C1. TEMP_beh exists
- [x] sub-0011/ses-03/func/sub-0011_ses-03_task-social_acq-mb8_run-02_events.tsv → #C1. TEMP_beh exists NEGATIVE ONSET
- [x] sub-0011/ses-04/func/sub-0011_ses-04_task-social_acq-mb8_run-01_events.tsv  → #C1. TEMP_beh exists NEGATIVE ONSET
- [x] sub-0013/ses-01/func/sub-0013_ses-01_task-social_acq-mb8_run-03_events.tsv → #C1. TEMP_beh exists
- [x] sub-0014/ses-01/func/sub-0014_ses-01_task-social_acq-mb8_run-02_events.tsv → #C1. TEMP_beh exists
- [x] sub-0014/ses-02/func/sub-0014_ses-02_task-narratives_acq-mb8_run-01_events.tsv → #C4. No TEMP file. MANUAL INSERT ERROR: phantom
- [x] sub-0016/ses-04/func/sub-0016_ses-04_task-alignvideo_acq-mb8_run-01_events.tsv → # C3. change 156 to 16 NEGATIVE ONSET
- [x] sub-0016/ses-04/func/sub-0016_ses-04_task-alignvideo_acq-mb8_run-02_events.tsv → # C3. change 156 to 16 NEGATIVE ONSET
- [x] sub-0016/ses-04/func/sub-0016_ses-04_task-social_acq-mb8_run-03_events.tsv → #C1 TEMP_beh exists. partial data NEGATIVE ONSET
- [x] sub-0017/ses-01/func/sub-0017_ses-01_task-alignvideo_acq-mb8_run-04_events.tsv → #C1 TEMP_beh exists BOLD DOESN"T EXIST
- [x] sub-0017/ses-02/func/sub-0017_ses-02_task-alignvideo_acq-mb8_run-01_events.tsv → #C1 TEMP_beh exists NEGATIVE ONSET
- [x] sub-0019/ses-03/func/sub-0019_ses-03_task-social_acq-mb8_run-02_events.tsv → #C1 TEMP_beh exists
- [ ] sub-0019/ses-04/func/sub-0019_ses-04_task-fractional_acq-mb8_run-01_events.tsv → #C2 files exists, but session number is wrong STILL → No func data  OPEN ISSUE. LIVES ON ROLANDO
- [ ] sub-0019/ses-04/func/sub-0019_ses-04_task-fractional_acq-mb8_run-02_events.tsv → #C2 files exists, but session number is wrong STILL → No func data OPEN ISSUE. LIVES ON ROLANDO
- [x] sub-0020/ses-04/func/sub-0020_ses-04_task-social_acq-mb8_run-06_events.tsv → # C1 TEMP_beh exists. NEGATIVE ONSET
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-alignvideo_acq-mb8_run-03_events.tsv → # C1 TEMP_beh exists NEGATIVE ONSET
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-01_events.tsv → #C3. TEMP_beh exist, but under sub-0098. NEED TO CHANGE ID. https://github.com/spatialtopology/d_beh/tree/master/sub-0021/task-social/ses-01
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-02_events.tsv→ #C3. TEMP_beh exist, but under sub-0098. NEED TO CHANGE ID. https://github.com/spatialtopology/d_beh/tree/master/sub-0021/task-social/ses-01
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-03_events.tsv → #C3. TEMP_beh exist, but under sub-0098. NEED TO CHANGE ID. https://github.com/spatialtopology/d_beh/tree/master/sub-0021/task-social/ses-01
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-04_events.tsv → #C3. TEMP_beh exist, but under sub-0098. NEED TO CHANGE ID. https://github.com/spatialtopology/d_beh/tree/master/sub-0021/task-social/ses-01
- [x] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-05_events.tsv → #C3. TEMP_beh exist, but under sub-0098. NEED TO CHANGE ID. https://github.com/spatialtopology/d_beh/tree/master/sub-0021/task-social/ses-01
- [x] sub-0023/ses-04/func/sub-0023_ses-04_task-social_acq-mb8_run-02_events.tsv → #C1 TEMP_beh exists NEGATIVE ONSET
- [X] sub-0024/ses-03/func/sub-0024_ses-03_task-social_acq-mb8_run-05_events.tsv → #C1 TEMP_beh exists
- [X] sub-0038/ses-02/func/sub-0038_ses-02_task-narratives_acq-mb8_run-03_events.tsv → #C1 TEMP_beh exists
- [X] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-01_events.tsv→ #C2
- [X] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-02_events.tsv→ #C2
- [X] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-03_events.tsv→ #C2
- [X] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-04_events.tsv→ #C2
- [ ] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-01_events.tsv → #C2 NEGATIVE DURATION
- [X] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-02_events.tsv → #C2
- [X] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-03_events.tsv → #C2
- [X] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-04_events.tsv → #C2
- [x] sub-0065/ses-04/func/sub-0065_ses-04_task-alignvideo_acq-mb8_run-02_events.tsv → #C1 TEMP_beh exists. NEGATIVE ONSET
- [x] sub-0066/ses-04/func/sub-0066_ses-04_task-social_acq-mb8_run-06_events.tsv → #C1 TEMP_beh exists. partial NEGATIVE ONSET
- [x] sub-0069/ses-02/func/sub-0069_ses-02_task-alignvideo_acq-mb8_run-04_events.tsv → #C1 TEMP_beh exists. partial NEGATIVE ONSET
- [X] sub-0069/ses-02/func/sub-0069_ses-02_task-narratives_acq-mb8_run-03_events.tsv → Narratives: participant had to discontinue run 3 because of issue with glasses. Partial data collected. #C1. TEMP_beh exists.  partial data
- [x] sub-0075/ses-01/func/sub-0075_ses-01_task-social_acq-mb8_run-01_events.tsv → NEED TO RENAME FILE FIRST DONE via #97

- [X] sub-0076/ses-02/func/sub-0076_ses-02_task-faces_acq-mb8_run-03_events.tsv → #C1. TEMP_beh exists.  partial data
- [x] sub-0083/ses-04/func/sub-0083_ses-04_task-social_acq-mb8_run-02_events.tsv → #C1. TEMP_beh exists. The paradigm froze late into the run on one of the screens that shows others' ratings. Not sure how many were missed, but it was under a minute when that happened NEGATIVE ONSET
CHECK behavioral data (see how many trials were successfully collected @Heejung)
- [x] sub-0084/ses-03/func/sub-0084_ses-03_task-alignvideo_acq-mb8_run-01_events.tsv  → #C1. TEMP_beh exists.  for one trial. Still usable if just simply hyperaligning. 

- [x] sub-0087/ses-01/func/sub-0087_ses-01_task-alignvideo_acq-mb8_run-01_events.tsv → #C1. TEMP_beh exists. NEGATIVE ONSET
- [ ] sub-0088/ses-03/func/sub-0088_ses-03_task-social_acq-mb8_run-03_events.tsv → #C1. TEMP_beh exists. NEGATIVE ONSET
- [x] sub-0089/ses-01/func/sub-0089_ses-01_task-social_acq-mb8_run-04_events.tsv → #C1. TEMP_beh exists. 
- [x] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-01_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-02_events.tsv  → #C2. Files exist. Check why not convert?
- [x] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-03_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-04_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0094/ses-04/func/sub-0094_ses-04_task-alignvideo_acq-mb8_run-01_events.tsv → #C1. TEMP_beh exists. NEGATIVE ONSET
- [x] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-01_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-02_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-03_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-04_events.tsv → #C2. Files exist. Check why not convert?
- [x] sub-0105/ses-02/func/sub-0105_ses-02_task-alignvideo_acq-mb8_run-02_events.tsv → #C1. TEMP_beh exists. Convert  NEGATIVE ONSET
- [x] sub-0112/ses-04/func/sub-0112_ses-04_task-social_acq-mb8_run-03_events.tsv → #C1. TEMP_beh exists. Convert NEGATIVE ONSET

**Comment by jungheejung** [comment]
- [ ] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-02_events.tsv
- [ ] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-03_events.tsv
- [ ] sub-0001/ses-01/func/sub-0001_ses-01_task-alignvideo_acq-mb8_run-04_events.tsv
- [ ] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [ ] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [ ] sub-0001/ses-02/func/sub-0001_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0001/ses-04/func/sub-0001_ses-04_task-fractional_acq-mb8_run-01_events.tsv
- [ ] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-01_events.tsv
- [ ] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0001/ses-04/func/sub-0001_ses-04_task-social_acq-mb8_run-03_events.tsv
- [ ] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [ ] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [ ] sub-0003/ses-02/func/sub-0003_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [ ] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [ ] sub-0004/ses-02/func/sub-0004_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [ ] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [ ] sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0006/ses-04/func/sub-0006_ses-04_task-fractional_acq-mb8_run-01_events.tsv
- [ ] sub-0006/ses-04/func/sub-0006_ses-04_task-fractional_acq-mb8_run-02_events.tsv
- [ ] sub-0007/ses-03/func/sub-0007_ses-03_task-social_acq-mb8_run-06_events.tsv
- [ ] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-01_events.tsv
- [ ] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-02_events.tsv
- [ ] sub-0008/ses-02/func/sub-0008_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0008/ses-04/func/sub-0008_ses-04_task-social_acq-mb8_run-05_events.tsv
- [ ] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0009/ses-02/func/sub-0009_ses-02_task-narratives_acq-mb8_run-04_events.tsv
- [ ] sub-0011/ses-02/func/sub-0011_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0011/ses-03/func/sub-0011_ses-03_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0011/ses-04/func/sub-0011_ses-04_task-social_acq-mb8_run-01_events.tsv
- [ ] sub-0013/ses-01/func/sub-0013_ses-01_task-social_acq-mb8_run-03_events.tsv
- [ ] sub-0014/ses-01/func/sub-0014_ses-01_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0014/ses-02/func/sub-0014_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0016/ses-04/func/sub-0016_ses-04_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0016/ses-04/func/sub-0016_ses-04_task-alignvideo_acq-mb8_run-02_events.tsv
- [ ] sub-0016/ses-04/func/sub-0016_ses-04_task-social_acq-mb8_run-03_events.tsv
- [ ] sub-0017/ses-01/func/sub-0017_ses-01_task-alignvideo_acq-mb8_run-04_events.tsv
- [ ] sub-0017/ses-02/func/sub-0017_ses-02_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0019/ses-03/func/sub-0019_ses-03_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0019/ses-04/func/sub-0019_ses-04_task-fractional_acq-mb8_run-01_events.tsv
- [ ] sub-0019/ses-04/func/sub-0019_ses-04_task-fractional_acq-mb8_run-02_events.tsv
- [ ] sub-0020/ses-04/func/sub-0020_ses-04_task-social_acq-mb8_run-06_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-alignvideo_acq-mb8_run-03_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-01_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-03_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-04_events.tsv
- [ ] sub-0021/ses-01/func/sub-0021_ses-01_task-social_acq-mb8_run-05_events.tsv
- [ ] sub-0023/ses-04/func/sub-0023_ses-04_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0024/ses-03/func/sub-0024_ses-03_task-social_acq-mb8_run-05_events.tsv
- [ ] sub-0038/ses-02/func/sub-0038_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0041/ses-02/func/sub-0041_ses-02_task-narratives_acq-mb8_run-04_events.tsv
- [ ] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0064/ses-02/func/sub-0064_ses-02_task-narratives_acq-mb8_run-04_events.tsv
- [ ] sub-0065/ses-04/func/sub-0065_ses-04_task-alignvideo_acq-mb8_run-02_events.tsv
- [ ] sub-0066/ses-04/func/sub-0066_ses-04_task-social_acq-mb8_run-06_events.tsv
- [ ] sub-0069/ses-02/func/sub-0069_ses-02_task-alignvideo_acq-mb8_run-04_events.tsv
- [ ] sub-0069/ses-02/func/sub-0069_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0075/ses-01/func/sub-0075_ses-01_task-social_acq-mb8_run-01_events.tsv
- [ ] sub-0076/ses-02/func/sub-0076_ses-02_task-faces_acq-mb8_run-03_events.tsv
- [ ] sub-0083/ses-04/func/sub-0083_ses-04_task-social_acq-mb8_run-02_events.tsv
- [ ] sub-0084/ses-03/func/sub-0084_ses-03_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0087/ses-01/func/sub-0087_ses-01_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0088/ses-03/func/sub-0088_ses-03_task-social_acq-mb8_run-03_events.tsv
- [ ] sub-0089/ses-01/func/sub-0089_ses-01_task-social_acq-mb8_run-04_events.tsv
- [ ] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0094/ses-02/func/sub-0094_ses-02_task-narratives_acq-mb8_run-04_events.tsv
- [ ] sub-0094/ses-04/func/sub-0094_ses-04_task-alignvideo_acq-mb8_run-01_events.tsv
- [ ] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-01_events.tsv
- [ ] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-02_events.tsv
- [ ] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-03_events.tsv
- [ ] sub-0103/ses-02/func/sub-0103_ses-02_task-narratives_acq-mb8_run-04_events.tsv
- [ ] sub-0105/ses-02/func/sub-0105_ses-02_task-alignvideo_acq-mb8_run-02_events.tsv
- [ ] sub-0112/ses-04/func/sub-0112_ses-04_task-social_acq-mb8_run-03_events.tsv

**Comment by jungheejung** [comment]
```
commit 2460ccb8ffc7c30e008e7ae9873255e771b99d85
Author: jungheejung <heejung.jung@colorado.edu>
Date:   Sun Sep 1 14:30:16 2024 -0400

    [DATALAD RUNCMD] DEV: convert BIDS file after resolving filename typo sub-0005_ses-02_task-faces_run-03
    
    === Do not change lines below ===
    {
     "chain": [],
     "cmd": "python ./code/spacetop-prep/spacetop_prep/events/bidsify_faces_ENH.py --bids_string sub-0005/ses-02/func/sub-0005_ses-02_task-faces_acq-mb8_run-03_events.tsv",
     "exit": 0,
     "extra_inputs": [],
     "inputs": [],
     "outputs": [],
     "pwd": "."
    }
    ^^^ Do not change lines above ^^^
```

**Comment by yarikoptic** [comment]
```
❯ git grep TODO -- sub*
```

empty so all done
